version: 0.2

phases:
  install:
    commands:
      #- git clone https://github.com/byu-oit/lambda_utils.git utils
      pip install -r requirements.txt -t .
  pre_build:
    commands:
      - pip install pytest
      - pytest -v
  build:
    commands:
      #- echo "Nothing to run in the build phase..."
  post_build:
    commands:
      #- echo "Nothing to run in the post_build phase..."
artifacts:
  files:
    - '**/*'
  discard-paths: no