# You need to make your exchange calendar public and then post the URL here
# Go to https://mail.byu.edu
# Click Calendar in the blue top bar
# Right click on the calendar called 'Calendar' under MY CALENDARS on the left sidebar
# Click "Permissions"
# Use the drop down to select "Limited details"
# Press SAVE
# Right click on the calendar called 'Calendar' under MY CALENDARS on the left sidebar
# Click "Permissions"
# Right click on "Subscribe to calendar" and select "Copy Link Address"
# paste that as the value of calendar_url here
calendar_url: http://mail.byu.edu/owa/calendar/blahblahblah/Calendar/calendar.ics

# Go to https://api.slack.com/apps
# Click "Create New App"
# Enter "ical2slackstatus" in App Name and select BYU/OIT in Development Slack Team and then click "Create App"
# Click "Oauth & Permissions"
# Under "Scopes"->"Select Permission Scopes", Select "Modify user’s profile. (users.profile:write)"
# Click "Save Changes"
# At the top of the page, click "Install App to Team"
# Click "Authorize"
# Copy your OAuth Access Token and paste it below
token: xoxp-1234567890-1234567890-123456789012-12abcd1ef234567fab890cd1ef2345ab
